url: "https://joshfriedman.dev"
baseurl: ""
title: "Josh Friedman"
description: "Josh Friedman: Developer, Musician, Athlete"
author: "Josh Friedman"
logo: "/assets/img/JoshFriedman-logo.png"

email: friedman.josh03@gmail.com
phone: (416) 843-6670
resume_tagline: Grade 12 Student @ William Lyon Mackenzie CI

contact_links:
  - name: Email
    url: mailto:friedman.josh03@gmail.com
    icon: fas fa-envelope
  - name: Linkedin
    url: https://www.linkedin.com/in/josh-friedman-1b9222199/
    icon: fab fa-linkedin
  - name: Github
    url: https://github.com/Jwiggiff
    icon: fab fa-github
  - name: CodePen
    url: https://codepen.io/jwiggiff
    icon: fab fa-codepen
  - name: Fiverr
    url: https://www.fiverr.com/share/Wo8dq7
    icon: https://unpkg.com/simple-icons@v4/icons/fiverr.svg
    not_fa: true

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/JoshFriedman-logo.png"

plugins:
  - jekyll-seo-tag
